name: Build Static Library

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Generate Solution File
      run: |
        msbuild /t:GenerateSolution
        ls **/*.sln

    - name: Build Project
      run: msbuild /p:Configuration=Release

    - name: Upload Static Library
      uses: actions/upload-artifact@v2
      with:
        name: Static Library
        path: lib/Release/logger.lib
